apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-pdfkzbgv
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-pdfkzbgv:f8369caad58965b2da48436c30a05b6ffb0cd1e0@sha256:a9504209a7a7d1627267695ace24dca6642b22d6df320c977cc50ef0965d2bd0
          name: container-image
